name: Test Full Build
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Test Full Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win32,win64]
        variant: [nonfree,nonfree-shared,nonfree 4.4,nonfree-shared 4.4]
        include:
          - target: linux64
            variant: nonfree
          - target: linux64
            variant: nonfree 4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkit.toml
          driver-opts: image=moby/buildkit:v0.9.1
      - name: Build Image
        run: ./makeimage.sh ${{ matrix.target }} ${{ matrix.variant }}
      - name: Build ffmpeg
        run: ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: artifacts/*
